name: deploy

on:
  push:
    branches:
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 18.9.1

      - name: Install dependencies
        run: npm ci

      - name: Decrypt secrets with gpg
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" \
           | sudo gpg --batch --passphrase-fd 0 --output "src/secrets/secret.dev.js" --decrypt "src/secrets/secret.dev.js.gpg" 
          echo "${{ secrets.GPG_PASSPHRASE }}" \
           | sudo gpg --batch --passphrase-fd 0 --output "src/secrets/secret.prd.js" --decrypt "src/secrets/secret.prd.js.gpg" 

      - name: Generate site
        run: |
          npm run generate
          # curl https://mirumi.in/sitemap.xml > .output/public/sitemap.xml
          # curl https://mirumi.in/feed > .output/public/feed.xml
          # curl https://mirumi.in/comments/feed > .output/public/feed-comments.xml

      - name: Sign in
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy files to S3
        run: |
          aws s3 sync \
            --delete \
            --region ap-northeast-1 \
            --cache-control "max-age=31536000" \
            .output/public/_nuxt/ s3://mirumime-prd-mirumi-me/_nuxt
          aws s3 sync \
            --delete \
            --region ap-northeast-1 \
            --cache-control "no-cache" \
            .output/public/ s3://mirumime-prd-mirumi-me
          aws cloudfront create-invalidation \
            --distribution-id E1UPWIMHFP5TEC \
            --paths "/*"
